name: Build & Test

on:
  push:
    branches:
      - "*"
  pull_request:
    types: [opened, reopened]
    branches:
      - "*"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, macos-14]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Cargo fmt
        run: cargo fmt --check

      - name: Cargo build (release)
        run: cargo build --release --all

      - name: Cargo test (release)
        run: cargo test --release --all
